

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    volumes:
      - backend_volume:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"

volumes:
  backend_volume:
    driver: local