

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-net
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    volumes:
      - backend_volume:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    networks:
      - app-net
    depends_on:
      - backend
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  backend_volume:
    driver: local

networks:
  app-net:
    driver: bridge